apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: admissionpolicies.policies.replicated.com
spec:
  group: policies.replicated.com
  names:
    kind: AdmissionPolicy
    plural: admissionpolicies
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              type: string
            policy:
              type: string
          required:
          - name
          - policy
          type: object
        status:
          type: object
  version: v1alpha2
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
