apiVersion: controllers.replicated.com/v1alpha1
kind: OpenPolicyAgent
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openpolicyagent-sample
spec:
  name: gatekeeper
  enabledFailureModes:
    ignore: true
    fail: false
