apiVersion: policies.replicated.com/v1alpha2
kind: AdmissionPolicy
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: no-latest-tags
spec:
  policy: |
    package kubernetes.admission

    deny[msg] {
        input.request.kind.kind = "Pod"
        input.request.operation = "CREATE"
        endswith(input.request.object.spec.containers[_].image, ":latest")
        msg = "pod contains image using latest tag"
    }
